nginx_ppa_use: true
nginx_ppa_version: stable
nginx_server_names_hash_bucket_size: "256"
nginx_vhosts:
  - listen:
      - "80 default_server"
      - "443 ssl"
    server_name: "nginx.gibzzz.ml"
    root: "/var/www/nginx.ansible.gibzzz.tk"
    index: "index.php index.html index.htm"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
