nginx_ppa_use: true
nginx_ppa_version: stable
nginx_server_names_hash_bucket_size: "256"
nginx_extra_http_options: |
  ssl_session_cache           shared:SSL:10m;
  ssl_session_timeout         5m;
  ssl_prefer_server_ciphers   on;
  ssl_stapling                on;
  resolver                    8.8.8.8;
nginx_vhosts:
  - listen:
      - "80 default_server"
      - "443 ssl"
    server_name: "nginx.gibzzz.ml"
    root: "/var/www/nginx.ansible.gibzzz.tk"
    index: "index.php index.html index.htm"
    keepalive_timeout: 60
    ssl_certificate: "/etc/letsencrypt/live/nginx.gibzzz.ml/chain.pem"
    ssl_certificate_key: "/etc/letsencrypt/live/nginx.gibzzz.ml/privkey.pem"
    ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"
    ssl_ciphers:  "HIGH:!RC4:!aNULL:!MD5:!kEDH"
    add_header: "Strict-Transport-Security 'max-age=604800'"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
