---

rabbitmq_erlang_cookie: 1qa2ws3ed
rabbitmq_ulimit_open_files: 1024
rabbitmq_memory_high_watermark: 0.4
rabbitmq_create_cluster: no
rabbitmq_cluster_master: localhost
rabbitmq_vhosts: []
rabbitmq_use_longname: 'false'

rabbitmq_logrotate_period: weekly
rabbitmq_logrotate_amount: 20

rabbitmq_amqp_port: 5672
rabbitmq_epmd_port: 4369
rabbitmq_node_port: 25672

rabbitmq_instant_queues: false
rabbitmq_instant_shovels: false

rabbitmq_plugins:
  - rabbitmq_management
  - rabbitmq_management_agent

rabbitmq_users:
  - user: admin
    password: admin
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator

rabbitmq_users_removed:
  - guest

rabbitmq_vhosts_queues:
  - vhost_name:
    queues: []
    user:
    password:
    durable: 'true'

##   Requares additional plugin enabled: rabbitmq_shovel
##   See https://www.rabbitmq.com/shovel-dynamic.html for json format
rabbitmq_shovels:
  -
    shovel_name:
    shovel_json: ''
  -
    shovel_name:
    shovel_json: ''
