- hosts: web
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/php.yml
    - vars/nginx.yml
    - vars/letsencrypt.yml
    - vars/zabbix.yml
  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.php }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.letsencrypt }
    - { role: dj-wasabi.zabbix-agent }

- hosts: elastic
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/elastic.yml
    - vars/zabbix.yml
  roles:
    - { role: geerlingguy.elasticsearch }
    - { role: dj-wasabi.zabbix-agent }

- hosts: mysql
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/mysql.yml
    - vars/zabbix.yml
  roles:
    - { role: geerlingguy.mysql }
    - { role: dj-wasabi.zabbix-agent }

- hosts: redis
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/redis.yml
    - vars/zabbix.yml
  roles:
    - { role: geerlingguy.redis }
    - { role: dj-wasabi.zabbix-agent }

- hosts: symfony-rabbitmq
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/php.yml
    - vars/letsencrypt.yml
    - vars/rabbitmq.yml
    - vars/symfony.yml
    - vars/zabbix.yml
  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.php }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.letsencrypt }
    - { role: alexeymedvedchikov.rabbitmq }
    - { role: dj-wasabi.zabbix-agent }

