- hosts: web
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/php.yml
    - vars/nginx.yml
    - vars/letsencrypt.yml
  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.php }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.letsencrypt }

- hosts: elastic
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/elastic.yml
  roles:
    - { role: geerlingguy.elasticsearch }

- hosts: mysql
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/mysql.yml
  roles:
    - { role: geerlingguy.mysql }

- hosts: redis
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/redis.yml
  roles:
    - { role: geerlingguy.redis }

