require 'yaml'

nodes = [
  { :nodename => "adn-talks-ansible-1", :ip => '192.168.2.2', :box => 'ubuntu/xenial64', :ram => 1024 },
  { :nodename => "adn-talks-ansible-2", :ip => '192.168.2.3', :box => 'ubuntu/xenial64', :ram => 2048 },
  { :nodename => "adn-talks-ansible-3", :ip => '192.168.2.4', :box => 'ubuntu/xenial64' },
  { :nodename => "adn-talks-ansible-4", :ip => '192.168.2.5', :box => 'ubuntu/xenial64' },
  { :nodename => "adn-talks-ansible-5", :ip => '192.168.2.6', :box => 'ubuntu/xenial64', :ram => 2048 },
]

Vagrant.configure("2") do |config|
  nodes.each_with_index do |node, i|
    config.vm.define node[:nodename] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = "#{node[:nodename]}.box"
      nodeconfig.vm.network "public_network",
        bridge: 'enp3s0',
        use_dhcp_assigned_default_route: true

      # Ansible hack
      nodeconfig.ssh.insert_key = false

      memory = node[:ram] ? node[:ram] : 512;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end

      nodeconfig.vm.provision "shell", name: "set-ubuntu-passwd", inline: "echo -e \"pass\\npass\" | sudo passwd ubuntu"
      nodeconfig.vm.provision "shell",
        inline: "route add default gw 192.168.88.1"
      # default router ipv6
      nodeconfig.vm.provision "shell",
        inline: "route -A inet6 add default gw fc00::1 enp0s8"
      # delete default gw on eth0
      nodeconfig.vm.provision "shell",
        inline: "eval `route -n | awk '{ if ($8 ==\"enp0s3\") print \"route del default gw \" $2; }'`"
    end
  end
end
