require 'yaml'

nodes = [
  { :nodename => "adn-talks-ansible-1", :ip => '192.168.2.2', :box => 'ubuntu/xenial64', :ram => 1024 },
  { :nodename => "adn-talks-ansible-2", :ip => '192.168.2.3', :box => 'ubuntu/xenial64', :ram => 2048 },
  { :nodename => "adn-talks-ansible-3", :ip => '192.168.2.4', :box => 'ubuntu/xenial64' },
  { :nodename => "adn-talks-ansible-4", :ip => '192.168.2.5', :box => 'ubuntu/xenial64' },
]

Vagrant.configure("2") do |config|
  nodes.each_with_index do |node, i|
    config.vm.define node[:nodename] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = "#{node[:nodename]}.box"
      nodeconfig.vm.network "public_network"

      # Ansible hack
      nodeconfig.ssh.insert_key = false

      memory = node[:ram] ? node[:ram] : 512;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end

      nodeconfig.vm.provision "shell", name: "set-ubuntu-passwd", inline: "echo -e \"pass\\npass\" | sudo passwd ubuntu"
    end
  end
end
