require 'yaml'

nodes = [
  { :nodename => "adn-talks-salt-1", :ip => '192.168.1.2', :box => 'ubuntu/xenial64', :roles => ['apt', 'vim', 'apache'], :ram => 1024 },
  { :nodename => "adn-talks-salt-2", :ip => '192.168.1.3', :box => 'ubuntu/xenial64', :roles => ['apt', 'elasticsearch'], :ram => 2048 },
  { :nodename => "adn-talks-salt-3", :ip => '192.168.1.4', :box => 'ubuntu/xenial64', :roles => ['apt', 'mysql'] },
  { :nodename => "adn-talks-salt-4", :ip => '192.168.1.5', :box => 'ubuntu/xenial64', :roles => ['apt', 'redis'] },
]

Vagrant.configure("2") do |config|
  nodes.each_with_index do |node, i|
    config.vm.define node[:nodename] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = "#{node[:nodename]}.box"
      nodeconfig.vm.network "public_network",
        bridge: 'enp3s0',
        use_dhcp_assigned_default_route: true

      memory = node[:ram] ? node[:ram] : 512;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end

      nodeconfig.vm.provision "shell",
        run: "always",
        inline: "route add default gw 192.168.88.1"
      # default router ipv6
      nodeconfig.vm.provision "shell",
        run: "always",
        inline: "route -A inet6 add default gw fc00::1 enp0s8"
      # delete default gw on eth0
      nodeconfig.vm.provision "shell",
        run: "always",
        inline: "eval `route -n | awk '{ if ($8 ==\"enp0s3\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"

      nodeconfig.vm.provision "shell", name: "check-salt", inline: "ping -c4 salt-master.local", run: "never"
      nodeconfig.vm.provision "shell", 
        inline: "wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2016.11.2/SALTSTACK-GPG-KEY.pub | sudo apt-key add -"
      nodeconfig.vm.provision "shell", 
        inline: "echo \"deb https://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2016.11.2 xenial main\" > /etc/apt/sources.list.d/saltstack.list"
      nodeconfig.vm.provision "shell", 
        inline: "apt-get update -y"
      nodeconfig.vm.provision "shell", 
        inline: "apt-get install salt-minion -y"
      nodeconfig.vm.provision "shell", 
        inline: "systemctl enable salt-minion"
      nodeconfig.vm.provision "shell",
        inline: "echo \"master: salt-master.local\" > /etc/salt/minion.d/master.conf"

      cnf = YAML::load(File.open('grains.conf'))
      cnf["grains"]["roles"] = node[:roles]
      nodeconfig.vm.provision "shell", inline: "echo \"#{cnf.to_yaml}\" > /etc/salt/minion.d/grains.conf"

      nodeconfig.vm.provision "shell",
        inline: "systemctl start salt-minion"
    end
  end
end
